### ISSUE TITLE
Prepare all the data for publishing on Joget market place

### ISSUE THREAD

**Issue by petrvecera** [profiq/joget-advanced-json-binder#2]
<img width="1167" alt="image" src="https://github.com/profiq/joget-advanced-json-binder/assets/8086995/8d3cf7a7-fa0d-464d-b0e0-ac892b183a46">

- [x] brief description
- [x] full description
- [x] icon
- [x] screenshots
- [x] video/slide/brochure
- [x] tutorial app

**Comment by dhrdlicka** [comment]
<details>
<summary>screenshots</summary>

![Screenshot from 2024-03-01 10-29-43](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/0d04bb1d-e55d-4dec-a5d9-983e7bbe0c7c)

![Screenshot from 2024-03-01 10-12-06](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/5fbfecd1-4a14-46ea-88f8-b9ccca792fe9)

![Screenshot from 2024-03-01 10-11-54](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/fac2c8de-96b8-4231-9229-13b4826e5349)

![Screenshot from 2024-03-01 10-26-14](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/0dfa85b2-4362-4b18-a855-6968c0a2d87b)

![Screenshot from 2024-03-01 10-31-59](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/8def4682-0924-44aa-b056-f7e12eef985b)

</details>

Maybe we could add some text labels onto the screenshots to describe what's going on in each of them.

**Comment by dhrdlicka** [comment]
[Screencast from 2024-03-01 13-18-03.webm](https://github.com/profiq/joget-advanced-json-binder/assets/13226155/0416785e-5e0a-48fb-add0-b5ec17b7cb65)

**Comment by petrvecera** [comment]
Info under the line:
Hi, this plugin builds on top of already included functionality in Joget (https://github.com/jogetworkflow/jw-community), we are using this in our project and wanted to share it with other people too. We are also happy to make a PR to the joget jw-community repository if you think it's more suitable. 

We have also created a DEMO application showcasing the usage of the plugin. 
We will send out request for the DEMO App shortly. 

Looking forward to your feedback.
